version: "3"

services:
  web:
    build:
      context: express-ts-master
      args:
        nodeEnv: development
    command: yarn run start-dev
    volumes:
      - ./dist:/app/dist
    ports:
      - "8080:8080"
      - "9229:9229"